// nextjs_deve/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./nextjs_deve/app/_components/Footer";
import SideMenu from "./nextjs_deve/app/_components/SideMenu";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dietgen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
     
          <div className="min-h-screen grid lg:grid-cols-[15vw_1fr] grid-rows-[1fr_auto]">
            {/* Sidebar */}
            <div className="hidden lg:block">
              <SideMenu />
            </div>

            {/* Content */}
            <div className="overflow-y-auto">
              {children}
            </div>

            {/* Footer */}
            <div className="lg:col-span-2">
              <Footer />
            </div>
          </div>
       
      </body>
    </html>
  );
}
